### ISSUE TITLE
gcc asan findings

### ISSUE THREAD

**Issue by chipitsine** [InHavk/libhercules#4]
```
==43105==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 44 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x407f43 in container_add_tag_Vector src/libhercules.c:300
    #2 0x4053d3 in test_event_to_binary test/Testlibhercules.c:265
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405af2 in main test/Testlibhercules.c:309
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 41 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x407458 in container_add_tag_Integer src/libhercules.c:212
    #2 0x4054fa in test_event_to_binary test/Testlibhercules.c:268
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405af2 in main test/Testlibhercules.c:309
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x406196 in event_create src/libhercules.c:34
    #2 0x401664 in test_event_with_container test/Testlibhercules.c:37
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x407f43 in container_add_tag_Vector src/libhercules.c:300
    #2 0x4055d3 in test_event_to_binary test/Testlibhercules.c:270
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405af2 in main test/Testlibhercules.c:309
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 35 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x407ae8 in container_add_tag_String src/libhercules.c:267
    #2 0x4052ef in test_event_to_binary test/Testlibhercules.c:262
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405af2 in main test/Testlibhercules.c:309
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 33 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x407c29 in container_add_tag_UUID src/libhercules.c:279
    #2 0x405387 in test_event_to_binary test/Testlibhercules.c:264
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405af2 in main test/Testlibhercules.c:309
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 33 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x407e39 in container_add_tag_Null src/libhercules.c:290
    #2 0x405336 in test_event_to_binary test/Testlibhercules.c:263
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405af2 in main test/Testlibhercules.c:309
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x404e39 in test_event_to_binary test/Testlibhercules.c:241
    #2 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #3 0x405af2 in main test/Testlibhercules.c:309
    #4 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x401482 in test_event_create test/Testlibhercules.c:23
    #2 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #3 0x405abc in main test/Testlibhercules.c:307
    #4 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x410c87 in list_create (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410c87)
    #2 0x40805f in container_add_tag_Vector src/libhercules.c:306
    #3 0x4055d3 in test_event_to_binary test/Testlibhercules.c:270
    #4 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #5 0x405af2 in main test/Testlibhercules.c:309
    #6 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x410c87 in list_create (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410c87)
    #2 0x40805f in container_add_tag_Vector src/libhercules.c:306
    #3 0x4053d3 in test_event_to_binary test/Testlibhercules.c:265
    #4 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #5 0x405af2 in main test/Testlibhercules.c:309
    #6 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x401622 in test_event_with_container test/Testlibhercules.c:34
    #2 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #3 0x405ad7 in main test/Testlibhercules.c:308
    #4 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x407458 in container_add_tag_Integer src/libhercules.c:212
    #2 0x401fab in test_event_with_container test/Testlibhercules.c:72
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 31 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x4079a4 in container_add_tag_Double src/libhercules.c:256
    #2 0x403184 in test_event_with_container test/Testlibhercules.c:136
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 31 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x407ae8 in container_add_tag_String src/libhercules.c:267
    #2 0x4035da in test_event_with_container test/Testlibhercules.c:152
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 30 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x407848 in container_add_tag_Float src/libhercules.c:245
    #2 0x402cfb in test_event_with_container test/Testlibhercules.c:120
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 30 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x407300 in container_add_tag_Short src/libhercules.c:201
    #2 0x401b2d in test_event_with_container test/Testlibhercules.c:56
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 29 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x407e39 in container_add_tag_Null src/libhercules.c:290
    #2 0x403e0e in test_event_with_container test/Testlibhercules.c:185
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 29 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x4076f2 in container_add_tag_Flag src/libhercules.c:234
    #2 0x40287a in test_event_with_container test/Testlibhercules.c:104
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 29 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x4075af in container_add_tag_Long src/libhercules.c:223
    #2 0x402428 in test_event_with_container test/Testlibhercules.c:88
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 29 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x4071a9 in container_add_tag_Byte src/libhercules.c:190
    #2 0x4016b7 in test_event_with_container test/Testlibhercules.c:40
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 29 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x407c29 in container_add_tag_UUID src/libhercules.c:279
    #2 0x403a14 in test_event_with_container test/Testlibhercules.c:169
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x410d1c in list_append (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410d1c)
    #2 0x407bf4 in container_add_tag_String src/libhercules.c:274
    #3 0x4035da in test_event_with_container test/Testlibhercules.c:152
    #4 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #5 0x405ad7 in main test/Testlibhercules.c:308
    #6 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x410d1c in list_append (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410d1c)
    #2 0x407ab4 in container_add_tag_Double src/libhercules.c:262
    #3 0x403184 in test_event_with_container test/Testlibhercules.c:136
    #4 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #5 0x405ad7 in main test/Testlibhercules.c:308
    #6 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x410d1c in list_append (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410d1c)
    #2 0x40796f in container_add_tag_Float src/libhercules.c:251
    #3 0x402cfb in test_event_with_container test/Testlibhercules.c:120
    #4 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #5 0x405ad7 in main test/Testlibhercules.c:308
    #6 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x410d1c in list_append (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410d1c)
    #2 0x407813 in container_add_tag_Flag src/libhercules.c:240
    #3 0x40287a in test_event_with_container test/Testlibhercules.c:104
    #4 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #5 0x405ad7 in main test/Testlibhercules.c:308
    #6 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x410d1c in list_append (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410d1c)
    #2 0x4076bd in container_add_tag_Long src/libhercules.c:229
    #3 0x402428 in test_event_with_container test/Testlibhercules.c:88
    #4 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #5 0x405ad7 in main test/Testlibhercules.c:308
    #6 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x410d1c in list_append (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410d1c)
    #2 0x40757b in container_add_tag_Integer src/libhercules.c:218
    #3 0x401fab in test_event_with_container test/Testlibhercules.c:72
    #4 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #5 0x405ad7 in main test/Testlibhercules.c:308
    #6 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x410d1c in list_append (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410d1c)
    #2 0x407425 in container_add_tag_Short src/libhercules.c:207
    #3 0x401b2d in test_event_with_container test/Testlibhercules.c:56
    #4 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #5 0x405ad7 in main test/Testlibhercules.c:308
    #6 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x410d1c in list_append (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410d1c)
    #2 0x407f0f in container_add_tag_Null src/libhercules.c:295
    #3 0x403e0e in test_event_with_container test/Testlibhercules.c:185
    #4 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #5 0x405ad7 in main test/Testlibhercules.c:308
    #6 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x410d1c in list_append (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410d1c)
    #2 0x407e05 in container_add_tag_UUID src/libhercules.c:285
    #3 0x403a14 in test_event_with_container test/Testlibhercules.c:169
    #4 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #5 0x405ad7 in main test/Testlibhercules.c:308
    #6 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x410d1c in list_append (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410d1c)
    #2 0x4072ca in container_add_tag_Byte src/libhercules.c:196
    #3 0x4016b7 in test_event_with_container test/Testlibhercules.c:40
    #4 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #5 0x405ad7 in main test/Testlibhercules.c:308
    #6 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x407cc5 in container_add_tag_UUID src/libhercules.c:283
    #2 0x403a14 in test_event_with_container test/Testlibhercules.c:169
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x410c87 in list_create (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410c87)
    #2 0x4061a4 in event_create src/libhercules.c:35
    #3 0x401664 in test_event_with_container test/Testlibhercules.c:37
    #4 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #5 0x405ad7 in main test/Testlibhercules.c:308
    #6 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 12 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x407b9a in container_add_tag_String src/libhercules.c:272
    #2 0x4035da in test_event_with_container test/Testlibhercules.c:152
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x40764b in container_add_tag_Long src/libhercules.c:227
    #2 0x402428 in test_event_with_container test/Testlibhercules.c:88
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x407a40 in container_add_tag_Double src/libhercules.c:260
    #2 0x403184 in test_event_with_container test/Testlibhercules.c:136
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x4074f4 in container_add_tag_Integer src/libhercules.c:216
    #2 0x401fab in test_event_with_container test/Testlibhercules.c:72
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x4078e4 in container_add_tag_Float src/libhercules.c:249
    #2 0x402cfb in test_event_with_container test/Testlibhercules.c:120
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 2 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x40739c in container_add_tag_Short src/libhercules.c:205
    #2 0x401b2d in test_event_with_container test/Testlibhercules.c:56
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x40778e in container_add_tag_Flag src/libhercules.c:238
    #2 0x40287a in test_event_with_container test/Testlibhercules.c:104
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Indirect leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x7f66f2b4d667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x407245 in container_add_tag_Byte src/libhercules.c:194
    #2 0x4016b7 in test_event_with_container test/Testlibhercules.c:40
    #3 0x410a91 in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410a91)
    #4 0x405ad7 in main test/Testlibhercules.c:308
    #5 0x7f66f28fa041 in __libc_start_main (/lib64/libc.so.6+0x27041)

SUMMARY: AddressSanitizer: 957 byte(s) leaked in 42 allocation(s).
```

**Comment by chipitsine** [comment]
осталось вот так 

```
=================================================================
==37666==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f5b5acc7667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x401600 in test_event_with_container test/Testlibhercules.c:34
    #2 0x40ffab in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x40ffab)
    #3 0x406c59 in main test/Testlibhercules.c:380
    #4 0x7f5b5aa74041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f5b5acc7667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x410169 in list_create (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410169)
    #2 0x40898d in container_add_tag_Vector src/libhercules.c:254
    #3 0x404e5c in test_event_with_container test/Testlibhercules.c:257
    #4 0x40ffab in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x40ffab)
    #5 0x406c59 in main test/Testlibhercules.c:380
    #6 0x7f5b5aa74041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f5b5acc7667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x405fbb in test_event_to_binary test/Testlibhercules.c:313
    #2 0x40ffab in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x40ffab)
    #3 0x406c74 in main test/Testlibhercules.c:381
    #4 0x7f5b5aa74041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f5b5acc7667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x410169 in list_create (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410169)
    #2 0x40898d in container_add_tag_Vector src/libhercules.c:254
    #3 0x406555 in test_event_to_binary test/Testlibhercules.c:337
    #4 0x40ffab in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x40ffab)
    #5 0x406c74 in main test/Testlibhercules.c:381
    #6 0x7f5b5aa74041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f5b5acc7667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x410169 in list_create (/home/ilia/inhavk/libhercules/build/libhercules.out+0x410169)
    #2 0x40898d in container_add_tag_Vector src/libhercules.c:254
    #3 0x406755 in test_event_to_binary test/Testlibhercules.c:342
    #4 0x40ffab in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x40ffab)
    #5 0x406c74 in main test/Testlibhercules.c:381
    #6 0x7f5b5aa74041 in __libc_start_main (/lib64/libc.so.6+0x27041)

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f5b5acc7667 in __interceptor_malloc (/lib64/libasan.so.6+0xb0667)
    #1 0x401462 in test_event_create test/Testlibhercules.c:23
    #2 0x40ffab in UnityDefaultTestRun (/home/ilia/inhavk/libhercules/build/libhercules.out+0x40ffab)
    #3 0x406c3e in main test/Testlibhercules.c:379
    #4 0x7f5b5aa74041 in __libc_start_main (/lib64/libc.so.6+0x27041)

SUMMARY: AddressSanitizer: 96 byte(s) leaked in 6 allocation(s).
```
